### ISSUE TITLE
Create customized RPI4 image with ROS 2 benchmarks

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/rpi4-rt-benchmarks-image#1]
@shuhaowu We are going to create in this repository a customized image including all the ROS 2 tools we use for https://ros-realtime.github.io/ros2_realtime_benchmarks/#introduction.

Not all the tools are available to install from binaries so we will need to crosscompile https://github.com/ros-realtime/reference-system. Also I think this tool requires colcon to run the benchmarks?

I see in the instructions that you include an example to something like this ([example-cross-compile](https://github.com/ros-realtime/ros-realtime-rpi4-image/blob/master/image_builder/data/example-cross-compile). 

How do you recommend to do it for this use case (crosscompile, compile in target using colcon, etc)?

**Comment by shuhaowu** [comment]
Cross-compilation **may** require a bit more effort to setup still. You can maybe try colcon build under emulation (so compile in the target-side scripts, instead of the host-side scripts) for now and see how slow it is? I would probably start there if I don't have a lot of time to work on this. If you have more time and are more adventurous, maybe can try cross compile? Not sure how it works with colcon yet as I haven't tried it with that yet.

**Comment by carlossvg** [comment]
FMI: 
- https://github.com/razr/hello-world-docker-action/blob/main/.github/workflows/cross-ros2.yaml
- https://daobook.github.io/ros2-docs/xin/How-To-Guides/Building-a-Custom-Debian-Package.html

**Comment by carlossvg** [comment]
FYI @razr @nightduck

**Comment by carlossvg** [comment]
@shuhaowu I had to increase the image size to 8GB because there was not enough space when building the tools

**Comment by carlossvg** [comment]
I created a release here: https://github.com/ros-realtime/rpi4-rt-benchmarks-image/releases/tag/22.04.1_v5.15.39-rt42-raspi_ros2_humble
